<script>
        var application_region = 'VICTORIA';


        var vr_blank_list = [];


        var vr_confirmation_types_list = [
            {"ref_name":"Yes", "display_name":"Yes", "display_order":"1"}, 
            {"ref_name":"No", "display_name":"No", "display_order":"2"} 
        ];


        var vr_input_types_list = [
            {"ref_name":"Select Box", "display_name":"Select Box", "display_order":"1"}, 
            {"ref_name":"Data Value", "display_name":"Data Value", "display_order":"2"}, 
            {"ref_name":"Blank", "display_name":"Blank", "display_order":"3"}, 
            {"ref_name":"Input Box", "display_name":"Input Box", "display_order":"4"}, 
            {"ref_name":"Input Box Caution", "display_name":"Input Box Caution", "display_order":"5"}, 
            {"ref_name":"Input Box Autofill", "display_name":"Input Box Autofill", "display_order":"6"}, 
            {"ref_name":"Hidden", "display_name":"Hidden", "display_order":"7"},  
            {"ref_name":"Image With Popup Show", "display_name":"Image With Popup Show", "display_order":"8"}, 
            {"ref_name":"Image With Popup Edit", "display_name":"Image With Popup Edit", "display_order":"9"} 
        ];


        var vr_framework_types_list = [
            {"ref_name":"Framework", "display_name":"Framework", "display_order":"1"}, 
            {"ref_name":"Drop-In", "display_name":"Drop-In", "display_order":"2"} 
        ];


        var vr_types_list = [
            {"ref_name":"VR0", "display_name":"Single Bay VR0", "display_order":"1", "bay_orientation":"vertical", "number_of_bay":"0", "bay_roof_shape":"flat"},
            {"ref_name":"VR1", "display_name":"Single Bay VR1", "display_order":"2", "bay_orientation":"vertical", "number_of_bay":"1", "bay_roof_shape":"flat"},
            {"ref_name":"VR2", "display_name":"Double Bay VR2", "display_order":"3", "bay_orientation":"vertical", "number_of_bay":"2", "bay_roof_shape":"flat"},
            {"ref_name":"VR3", "display_name":"Double Bay VR3", "display_order":"4", "bay_orientation":"horizontal", "number_of_bay":"2", "bay_roof_shape":"flat"},
            {"ref_name":"VR3G", "display_name":"Double Bay VR3 - Thru-Gutter", "display_order":"5", "bay_orientation":"horizontal", "number_of_bay":"2", "bay_roof_shape":"flat"},
            {"ref_name":"VR4", "display_name":"Triple Bay VR4", "display_order":"6", "bay_orientation":"vertical", "number_of_bay":"3", "bay_roof_shape":"flat"}, 
            {"ref_name":"VR5", "display_name":"Triple Bay VR5", "display_order":"7", "bay_orientation":"horizontal", "number_of_bay":"3", "bay_roof_shape":"flat"}, 
            {"ref_name":"VR6", "display_name":"Quadruple Bay VR6", "display_order":"8", "bay_orientation":"vertical", "number_of_bay":"4", "bay_roof_shape":"flat"}, 
            {"ref_name":"VR7", "display_name":"Quadruple Bay VR7", "display_order":"9", "bay_orientation":"horizontal", "number_of_bay":"4", "bay_roof_shape":"flat"}, 
            {"ref_name":"VR8", "display_name":"Double Bay VR8 - Gable", "display_order":"10", "bay_orientation":"vertical", "number_of_bay":"2", "bay_roof_shape":"gable"}, 
            {"ref_name":"VR9", "display_name":"Double Bay VR9 - Gable", "display_order":"11", "bay_orientation":"horizontal", "number_of_bay":"2", "bay_roof_shape":"gable"} 
        ];


        var vr_fractions_list = [
            {"ref_name":"1/32", "display_name":"1/32", "display_order":"1"}, 
            {"ref_name":"2/32", "display_name":"1/16", "display_order":"2"}, 
            {"ref_name":"3/32", "display_name":"3/32", "display_order":"3"}, 
            {"ref_name":"4/32", "display_name":"1/8", "display_order":"4"}, 
            {"ref_name":"5/32", "display_name":"5/32", "display_order":"5"}, 
            {"ref_name":"6/32", "display_name":"6/32", "display_order":"6"}, 
            {"ref_name":"7/32", "display_name":"7/32", "display_order":"7"}, 
            {"ref_name":"8/32", "display_name":"1/4", "display_order":"8"}, 
            {"ref_name":"9/32", "display_name":"9/32", "display_order":"9"}, 
            {"ref_name":"10/32", "display_name":"10/32", "display_order":"10"}, 
            {"ref_name":"11/32", "display_name":"11/32", "display_order":"11"}, 
            {"ref_name":"12/32", "display_name":"3/8", "display_order":"12"}, 
            {"ref_name":"13/32", "display_name":"13/32", "display_order":"13"}, 
            {"ref_name":"14/32", "display_name":"14/32", "display_order":"14"}, 
            {"ref_name":"15/32", "display_name":"15/32", "display_order":"15"}, 
            {"ref_name":"16/32", "display_name":"1/2", "display_order":"16"}, 
            {"ref_name":"17/32", "display_name":"17/32", "display_order":"17"}, 
            {"ref_name":"18/32", "display_name":"18/32", "display_order":"18"}, 
            {"ref_name":"19/32", "display_name":"19/32", "display_order":"19"}, 
            {"ref_name":"20/32", "display_name":"5/8", "display_order":"20"}, 
            {"ref_name":"21/32", "display_name":"21/32", "display_order":"21"}, 
            {"ref_name":"22/32", "display_name":"22/32", "display_order":"22"}, 
            {"ref_name":"23/32", "display_name":"23/32", "display_order":"23"}, 
            {"ref_name":"24/32", "display_name":"3/4", "display_order":"24"}, 
            {"ref_name":"25/32", "display_name":"25/32", "display_order":"25"}, 
            {"ref_name":"26/32", "display_name":"26/32", "display_order":"26"}, 
            {"ref_name":"27/32", "display_name":"27/32", "display_order":"27"}, 
            {"ref_name":"28/32", "display_name":"7/8", "display_order":"28"}, 
            {"ref_name":"29/32", "display_name":"29/32", "display_order":"29"}, 
            {"ref_name":"30/32", "display_name":"30/32", "display_order":"30"}, 
            {"ref_name":"31/32", "display_name":"31/32", "display_order":"31"}
        ];


        var vr_item_config_internal_ref_name_list = {
            "VR0":[
            ], 
            "VR1":[
                {"section_ref_name":"Frame", "ref_name":"beam_front_and_rear", "display_name":"Beam - Front and Rear"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_left_and_right", "display_name":"Beam - Left and Right"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow", "display_name":"Gutter - Narrow"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_wide", "display_name":"Gutter - Wide"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_narrow_to_wide", "display_name":"Gutter - Narrow to Wide"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_wide_to_narrow", "display_name":"Gutter - Wide to Narrow"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_lining", "display_name":"Gutter Lining"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front", "display_name":"Flashing Beam Face - Front"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_left_and_right", "display_name":"Flashing Beam Face - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_male", "display_name":"Flashing Adaptor - Male"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_female", "display_name":"Flashing Adaptor - Female"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_fascia", "display_name":"Flashing Fascia"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front", "display_name":"Flashing Perimeter - Front"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_left_and_right", "display_name":"Flashing Perimeter - Left and Right"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre", "display_name":"Vergola System - Louvre"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_endcap", "display_name":"Vergola System - Endcap"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip", "display_name":"Vergola System - Pivot Strip"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar", "display_name":"Vergola System - Link Bar"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_operator_motor", "display_name":"Vergola System - Operator Motor"} 
            ], 
            "VR2":[
                {"section_ref_name":"Frame", "ref_name":"beam_front_and_rear", "display_name":"Beam - Front and Rear"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_left_and_right", "display_name":"Beam - Left and Right"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_intermediate", "display_name":"Beam - Intermediate"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow_bay_1", "display_name":"Gutter - Narrow - Bay 1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow_bay_2", "display_name":"Gutter - Narrow - Bay 2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_wide_bay_1", "display_name":"Gutter - Wide - Bay 1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_wide_bay_2", "display_name":"Gutter - Wide - Bay 2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_narrow_to_wide", "display_name":"Gutter - Narrow to Wide"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_wide_to_narrow", "display_name":"Gutter - Wide to Narrow"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_lining", "display_name":"Gutter Lining"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front", "display_name":"Flashing Beam Face - Front"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_left_and_right", "display_name":"Flashing Beam Face - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_male", "display_name":"Flashing Adaptor - Male"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_female", "display_name":"Flashing Adaptor - Female"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_fascia", "display_name":"Flashing Fascia"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front", "display_name":"Flashing Perimeter - Front"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_left_and_right", "display_name":"Flashing Perimeter - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_intermediate", "display_name":"Flashing Intermediate"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_1", "display_name":"Vergola System - Louvre - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_2", "display_name":"Vergola System - Louvre - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_endcap", "display_name":"Vergola System - Endcap"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_1", "display_name":"Vergola System - Pivot Strip - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_2", "display_name":"Vergola System - Pivot Strip - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_1", "display_name":"Vergola System - Link Bar - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_2", "display_name":"Vergola System - Link Bar - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_operator_motor", "display_name":"Vergola System - Operator Motor"} 
            ], 
            "VR3":[
                {"section_ref_name":"Frame", "ref_name":"beam_front_and_rear", "display_name":"Beam - Front and Rear"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_left_and_right", "display_name":"Beam - Left and Right"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_intermediate", "display_name":"Beam - Intermediate"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow", "display_name":"Gutter - Narrow"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_wide", "display_name":"Gutter - Wide"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_narrow_to_wide_bay_1", "display_name":"Gutter - Narrow to Wide - Bay 1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_wide_to_narrow_bay_1", "display_name":"Gutter - Wide to Narrow - Bay 1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_narrow_to_wide_bay_2", "display_name":"Gutter - Narrow to Wide - Bay 2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_wide_to_narrow_bay_2", "display_name":"Gutter - Wide to Narrow - Bay 2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_lining", "display_name":"Gutter Lining"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front_bay_1", "display_name":"Flashing Beam Face - Front - Bay 1"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front_bay_2", "display_name":"Flashing Beam Face - Front - Bay 2"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_left_and_right", "display_name":"Flashing Beam Face - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_male", "display_name":"Flashing Adaptor - Male"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_female", "display_name":"Flashing Adaptor - Female"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_fascia", "display_name":"Flashing Fascia"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front_bay_1", "display_name":"Flashing Perimeter - Front - Bay 1"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front_bay_2", "display_name":"Flashing Perimeter - Front - Bay 2"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_left_and_right", "display_name":"Flashing Perimeter - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_intermediate", "display_name":"Flashing Intermediate"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_1", "display_name":"Vergola System - Louvre - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_2", "display_name":"Vergola System - Louvre - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_endcap", "display_name":"Vergola System - Endcap"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_1", "display_name":"Vergola System - Pivot Strip - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_2", "display_name":"Vergola System - Pivot Strip - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_1", "display_name":"Vergola System - Link Bar - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_2", "display_name":"Vergola System - Link Bar - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_operator_motor", "display_name":"Vergola System - Operator Motor"} 
            ], 
            "VR3G":[
                {"section_ref_name":"Frame", "ref_name":"beam_front_and_rear", "display_name":"Beam - Front and Rear"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_left_and_right", "display_name":"Beam - Left and Right"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_intermediate", "display_name":"Beam - Intermediate"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow", "display_name":"Gutter - Narrow"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_bridge", "display_name":"Gutter - Bridge"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_wide", "display_name":"Gutter - Wide"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_narrow_to_bridge_bay_1", "display_name":"Gutter - Narrow to Bridge - Bay 1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_bridge_to_narrow_bay_1", "display_name":"Gutter - Bridge to Narrow - Bay 1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_bridge_to_wide_bay_2", "display_name":"Gutter - Bridge to Wide - Bay 2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_wide_to_bridge_bay_2", "display_name":"Gutter - Wide to Bridge - Bay 2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_lining", "display_name":"Gutter Lining"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front_bay_1", "display_name":"Flashing Beam Face - Front - Bay 1"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front_bay_2", "display_name":"Flashing Beam Face - Front - Bay 2"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_left_and_right", "display_name":"Flashing Beam Face - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_male", "display_name":"Flashing Adaptor - Male"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_female", "display_name":"Flashing Adaptor - Female"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_fascia", "display_name":"Flashing Fascia"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front_bay_1", "display_name":"Flashing Perimeter - Front - Bay 1"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front_bay_2", "display_name":"Flashing Perimeter - Front - Bay 2"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_left_and_right", "display_name":"Flashing Perimeter - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_intermediate", "display_name":"Flashing Intermediate"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_1", "display_name":"Vergola System - Louvre - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_2", "display_name":"Vergola System - Louvre - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_endcap", "display_name":"Vergola System - Endcap"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_1", "display_name":"Vergola System - Pivot Strip - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_2", "display_name":"Vergola System - Pivot Strip - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_1", "display_name":"Vergola System - Link Bar - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_2", "display_name":"Vergola System - Link Bar - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_operator_motor", "display_name":"Vergola System - Operator Motor"} 
            ], 
            "VR4":[
                {"section_ref_name":"Frame", "ref_name":"beam_front_and_rear", "display_name":"Beam - Front and Rear"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_left_and_right", "display_name":"Beam - Left and Right"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_intermediate", "display_name":"Beam - Intermediate"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow_bay_1", "display_name":"Gutter - Narrow - Bay 1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow_bay_2", "display_name":"Gutter - Narrow - Bay 2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow_bay_3", "display_name":"Gutter - Narrow - Bay 3"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_wide_bay_1", "display_name":"Gutter - Wide - Bay 1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_wide_bay_2", "display_name":"Gutter - Wide - Bay 2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_wide_bay_3", "display_name":"Gutter - Wide - Bay 3"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_narrow_to_wide", "display_name":"Gutter - Narrow to Wide"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_wide_to_narrow", "display_name":"Gutter - Wide to Narrow"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_lining", "display_name":"Gutter Lining"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front", "display_name":"Flashing Beam Face - Front"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_left_and_right", "display_name":"Flashing Beam Face - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_male", "display_name":"Flashing Adaptor - Male"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_female", "display_name":"Flashing Adaptor - Female"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_fascia", "display_name":"Flashing Fascia"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front", "display_name":"Flashing Perimeter - Front"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_left_and_right", "display_name":"Flashing Perimeter - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_intermediate", "display_name":"Flashing Intermediate"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_1", "display_name":"Vergola System - Louvre - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_2", "display_name":"Vergola System - Louvre - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_3", "display_name":"Vergola System - Louvre - Bay 3"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_endcap", "display_name":"Vergola System - Endcap"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_1", "display_name":"Vergola System - Pivot Strip - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_2", "display_name":"Vergola System - Pivot Strip - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_3", "display_name":"Vergola System - Pivot Strip - Bay 3"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_1", "display_name":"Vergola System - Link Bar - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_2", "display_name":"Vergola System - Link Bar - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_3", "display_name":"Vergola System - Link Bar - Bay 3"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_operator_motor", "display_name":"Vergola System - Operator Motor"} 
            ], 
            "VR5":[
                {"section_ref_name":"Frame", "ref_name":"beam_front_and_rear", "display_name":"Beam - Front and Rear"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_left_and_right", "display_name":"Beam - Left and Right"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_intermediate", "display_name":"Beam - Intermediate"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow", "display_name":"Gutter - Narrow"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_wide", "display_name":"Gutter - Wide"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_narrow_to_wide_bay_1", "display_name":"Gutter - Narrow to Wide - Bay 1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_wide_to_narrow_bay_1", "display_name":"Gutter - Wide to Narrow - Bay 1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_narrow_to_wide_bay_2", "display_name":"Gutter - Narrow to Wide - Bay 2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_wide_to_narrow_bay_2", "display_name":"Gutter - Wide to Narrow - Bay 2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_narrow_to_wide_bay_3", "display_name":"Gutter - Narrow to Wide - Bay 3"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_wide_to_narrow_bay_3", "display_name":"Gutter - Wide to Narrow - Bay 3"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_lining", "display_name":"Gutter Lining"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front_bay_1", "display_name":"Flashing Beam Face - Front - Bay 1"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front_bay_2", "display_name":"Flashing Beam Face - Front - Bay 2"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front_bay_3", "display_name":"Flashing Beam Face - Front - Bay 3"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_left_and_right", "display_name":"Flashing Beam Face - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_male", "display_name":"Flashing Adaptor - Male"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_female", "display_name":"Flashing Adaptor - Female"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_fascia", "display_name":"Flashing Fascia"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front_bay_1", "display_name":"Flashing Perimeter - Front - Bay 1"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front_bay_2", "display_name":"Flashing Perimeter - Front - Bay 2"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front_bay_3", "display_name":"Flashing Perimeter - Front - Bay 3"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_left_and_right", "display_name":"Flashing Perimeter - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_intermediate", "display_name":"Flashing Intermediate"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_1", "display_name":"Vergola System - Louvre - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_2", "display_name":"Vergola System - Louvre - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_3", "display_name":"Vergola System - Louvre - Bay 3"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_endcap", "display_name":"Vergola System - Endcap"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_1", "display_name":"Vergola System - Pivot Strip - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_2", "display_name":"Vergola System - Pivot Strip - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_3", "display_name":"Vergola System - Pivot Strip - Bay 3"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_1", "display_name":"Vergola System - Link Bar - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_2", "display_name":"Vergola System - Link Bar - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_3", "display_name":"Vergola System - Link Bar - Bay 3"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_operator_motor", "display_name":"Vergola System - Operator Motor"} 
            ], 
            "VR6":[
                {"section_ref_name":"Frame", "ref_name":"beam_front_and_rear", "display_name":"Beam - Front and Rear"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_left_and_right", "display_name":"Beam - Left and Right"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_intermediate", "display_name":"Beam - Intermediate"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow_bay_1", "display_name":"Gutter - Narrow - Bay 1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow_bay_2", "display_name":"Gutter - Narrow - Bay 2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow_bay_3", "display_name":"Gutter - Narrow - Bay 3"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow_bay_4", "display_name":"Gutter - Narrow - Bay 4"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_wide_bay_1", "display_name":"Gutter - Wide - Bay 1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_wide_bay_2", "display_name":"Gutter - Wide - Bay 2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_wide_bay_3", "display_name":"Gutter - Wide - Bay 3"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_wide_bay_4", "display_name":"Gutter - Wide - Bay 4"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_narrow_to_wide", "display_name":"Gutter - Narrow to Wide"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_wide_to_narrow", "display_name":"Gutter - Wide to Narrow"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_lining", "display_name":"Gutter Lining"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front", "display_name":"Flashing Beam Face - Front"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_left_and_right", "display_name":"Flashing Beam Face - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_male", "display_name":"Flashing Adaptor - Male"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_female", "display_name":"Flashing Adaptor - Female"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_fascia", "display_name":"Flashing Fascia"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front", "display_name":"Flashing Perimeter - Front"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_left_and_right", "display_name":"Flashing Perimeter - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_intermediate", "display_name":"Flashing Intermediate"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_1", "display_name":"Vergola System - Louvre - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_2", "display_name":"Vergola System - Louvre - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_3", "display_name":"Vergola System - Louvre - Bay 3"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_4", "display_name":"Vergola System - Louvre - Bay 4"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_endcap", "display_name":"Vergola System - Endcap"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_1", "display_name":"Vergola System - Pivot Strip - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_2", "display_name":"Vergola System - Pivot Strip - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_3", "display_name":"Vergola System - Pivot Strip - Bay 3"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_4", "display_name":"Vergola System - Pivot Strip - Bay 4"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_1", "display_name":"Vergola System - Link Bar - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_2", "display_name":"Vergola System - Link Bar - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_3", "display_name":"Vergola System - Link Bar - Bay 3"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_4", "display_name":"Vergola System - Link Bar - Bay 4"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_operator_motor", "display_name":"Vergola System - Operator Motor"} 
            ], 
            "VR7":[
                {"section_ref_name":"Frame", "ref_name":"beam_front_and_rear", "display_name":"Beam - Front and Rear"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_left_and_right", "display_name":"Beam - Left and Right"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_intermediate", "display_name":"Beam - Intermediate"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow", "display_name":"Gutter - Narrow"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_wide", "display_name":"Gutter - Wide"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_narrow_to_wide_bay_1", "display_name":"Gutter - Narrow to Wide - Bay 1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_wide_to_narrow_bay_1", "display_name":"Gutter - Wide to Narrow - Bay 1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_narrow_to_wide_bay_2", "display_name":"Gutter - Narrow to Wide - Bay 2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_wide_to_narrow_bay_2", "display_name":"Gutter - Wide to Narrow - Bay 2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_narrow_to_wide_bay_3", "display_name":"Gutter - Narrow to Wide - Bay 3"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_wide_to_narrow_bay_3", "display_name":"Gutter - Wide to Narrow - Bay 3"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_narrow_to_wide_bay_4", "display_name":"Gutter - Narrow to Wide - Bay 4"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_wide_to_narrow_bay_4", "display_name":"Gutter - Wide to Narrow - Bay 4"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_lining", "display_name":"Gutter Lining"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front_bay_1", "display_name":"Flashing Beam Face - Front - Bay 1"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front_bay_2", "display_name":"Flashing Beam Face - Front - Bay 2"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front_bay_3", "display_name":"Flashing Beam Face - Front - Bay 3"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front_bay_4", "display_name":"Flashing Beam Face - Front - Bay 4"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_left_and_right", "display_name":"Flashing Beam Face - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_male", "display_name":"Flashing Adaptor - Male"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_female", "display_name":"Flashing Adaptor - Female"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_fascia", "display_name":"Flashing Fascia"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front_bay_1", "display_name":"Flashing Perimeter - Front - Bay 1"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front_bay_2", "display_name":"Flashing Perimeter - Front - Bay 2"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front_bay_3", "display_name":"Flashing Perimeter - Front - Bay 3"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front_bay_4", "display_name":"Flashing Perimeter - Front - Bay 4"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_left_and_right", "display_name":"Flashing Perimeter - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_intermediate", "display_name":"Flashing Intermediate"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_1", "display_name":"Vergola System - Louvre - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_2", "display_name":"Vergola System - Louvre - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_3", "display_name":"Vergola System - Louvre - Bay 3"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_4", "display_name":"Vergola System - Louvre - Bay 4"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_endcap", "display_name":"Vergola System - Endcap"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_1", "display_name":"Vergola System - Pivot Strip - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_2", "display_name":"Vergola System - Pivot Strip - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_3", "display_name":"Vergola System - Pivot Strip - Bay 3"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_4", "display_name":"Vergola System - Pivot Strip - Bay 4"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_1", "display_name":"Vergola System - Link Bar - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_2", "display_name":"Vergola System - Link Bar - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_3", "display_name":"Vergola System - Link Bar - Bay 3"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_4", "display_name":"Vergola System - Link Bar - Bay 4"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_operator_motor", "display_name":"Vergola System - Operator Motor"} 
            ], 
            "VR8":[
                {"section_ref_name":"Frame", "ref_name":"beam_front_and_rear_bay_1", "display_name":"Beam - Front and Rear - Bay 1"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_front_and_rear_bay_2", "display_name":"Beam - Front and Rear - Bay 2"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_left_and_right", "display_name":"Beam - Left and Right"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_intermediate", "display_name":"Beam - Intermediate"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow_bay_1_1", "display_name":"Gutter - Narrow - Bay 1.1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow_bay_1_2", "display_name":"Gutter - Narrow - Bay 1.2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow_bay_1_3", "display_name":"Gutter - Narrow - Bay 1.3"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow_bay_2_1", "display_name":"Gutter - Narrow - Bay 2.1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow_bay_2_2", "display_name":"Gutter - Narrow - Bay 2.2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow_bay_2_3", "display_name":"Gutter - Narrow - Bay 2.3"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_wide_bay_1", "display_name":"Gutter - Wide - Bay 1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_wide_bay_2", "display_name":"Gutter - Wide - Bay 2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_lining", "display_name":"Gutter Lining"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front_bay_1", "display_name":"Flashing Beam Face - Front - Bay 1"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front_bay_2", "display_name":"Flashing Beam Face - Front - Bay 2"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_left_and_right", "display_name":"Flashing Beam Face - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_male", "display_name":"Flashing Adaptor - Male"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_female", "display_name":"Flashing Adaptor - Female"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_fascia", "display_name":"Flashing Fascia"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front_bay_1", "display_name":"Flashing Perimeter - Front - Bay 1"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front_bay_2", "display_name":"Flashing Perimeter - Front - Bay 2"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_left_and_right", "display_name":"Flashing Perimeter - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_intermediate", "display_name":"Flashing Intermediate"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_1", "display_name":"Vergola System - Louvre - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_2", "display_name":"Vergola System - Louvre - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_endcap", "display_name":"Vergola System - Endcap"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_1", "display_name":"Vergola System - Pivot Strip - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_2", "display_name":"Vergola System - Pivot Strip - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_1", "display_name":"Vergola System - Link Bar - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_2", "display_name":"Vergola System - Link Bar - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_operator_motor", "display_name":"Vergola System - Operator Motor"} 
            ], 
            "VR9":[
                {"section_ref_name":"Frame", "ref_name":"beam_front_and_rear_bay_1", "display_name":"Beam - Front and Rear - Bay 1"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_front_and_rear_bay_2", "display_name":"Beam - Front and Rear - Bay 2"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_left_and_right", "display_name":"Beam - Left and Right"}, 
                {"section_ref_name":"Frame", "ref_name":"beam_intermediate", "display_name":"Beam - Intermediate"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_narrow", "display_name":"Gutter - Narrow"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_wide", "display_name":"Gutter - Wide"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_narrow_to_wide_bay_1", "display_name":"Gutter - Narrow to Wide - Bay 1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_wide_to_narrow_bay_1", "display_name":"Gutter - Wide to Narrow - Bay 1"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_narrow_to_wide_bay_2", "display_name":"Gutter - Narrow to Wide - Bay 2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_tapered_wide_to_narrow_bay_2", "display_name":"Gutter - Wide to Narrow - Bay 2"}, 
                {"section_ref_name":"Guttering", "ref_name":"gutter_lining", "display_name":"Gutter Lining"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front_bay_1", "display_name":"Flashing Beam Face - Front - Bay 1"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_front_bay_2", "display_name":"Flashing Beam Face - Front - Bay 2"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_beam_face_left_and_right", "display_name":"Flashing Beam Face - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_male", "display_name":"Flashing Adaptor - Male"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_adaptor_female", "display_name":"Flashing Adaptor - Female"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_fascia", "display_name":"Flashing Fascia"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front_bay_1", "display_name":"Flashing Perimeter - Front - Bay 1"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_front_bay_2", "display_name":"Flashing Perimeter - Front - Bay 2"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_perimeter_left_and_right", "display_name":"Flashing Perimeter - Left and Right"}, 
                {"section_ref_name":"Flashings", "ref_name":"flashing_intermediate", "display_name":"Flashing Intermediate"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_1", "display_name":"Vergola System - Louvre - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_louvre_bay_2", "display_name":"Vergola System - Louvre - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_endcap", "display_name":"Vergola System - Endcap"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_1", "display_name":"Vergola System - Pivot Strip - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_pivot_strip_bay_2", "display_name":"Vergola System - Pivot Strip - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_1", "display_name":"Vergola System - Link Bar - Bay 1"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_link_bar_bay_2", "display_name":"Vergola System - Link Bar - Bay 2"}, 
                {"section_ref_name":"Vergola", "ref_name":"vergola_system_operator_motor", "display_name":"Vergola System - Operator Motor"} 
            ], 
        };


        var vr_colours_list = <?php echo getResultsetInJson($sql_template_retrieve_colour_list); ?>;


        var vr_sections_list = <?php echo getResultsetInJson($sql_template_retrieve_section_list); ?>;


        var vr_subsections_list = <?php echo getResultsetInJson($sql_template_retrieve_subsection_list); ?>;


        var vr_items_list = <?php echo getResultsetInJson($sql_template_retrieve_item_list); ?>;

        var vr_items_list_hide_costing = <?php echo getResultsetInJson($sql_template_retrieve_item_list_hide_costing); ?>;
        
        <?php
        $sql = str_replace(
            array(
                '[PROJECT_ID]', 
                '[QUOTE_ID]'
            ), 
            array(
                $vr_form_system_info['project_id'], 
                $vr_form_system_info['quote_id']
            ), 
            $sql_template_retrieve_total_process_order_items_by_section_info
        );
        ?>
        var vr_total_process_order_items_by_section_list = <?php echo getResultsetInJson($sql); ?>;


        var vr_item_default_dimensions_list = <?php echo $vr_item_default_dimensions_list; ?>;


        var current_signed_in_user_access_profiles = <?php echo json_encode($current_signed_in_user_access_profiles); ?>;
</script>
