name: Deploy To Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: [self-hosted, vergola-vglwa-staging]

    steps:
      - name: Configure Git
        run: |
          git config --global user.email "vergola.github@knowdgeplus.net.au"
          git config --global user.name "kplus-vergola"
    
      - name: Deploy Application
        run: |
          cd C:/xampp/htdocs/VergolaVGLWA
          git branch -a
          git fetch -a
          git checkout -b staging origin/staging

          git pull origin staging
